version: "3.8"
services:
  postgres:
    hostname: ausleihe-db
    container_name: ausleihe-db
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data-ausleihe
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    hostname: ausleihe-app
    container_name: ausleihe-app
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres-data:
